name: alivechms
description: "The Official Church Management System for Meaningful Life Christian Centre"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  bitsdojo_window: ^0.1.6
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.19.0
  ionicons: ^0.2.2
  paged_datatable: ^2.1.1
  path_provider: ^2.1.4
  provider: ^6.1.2
  window_manager: ^0.3.9
  webb_ui:
    path: ../webb_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
